// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4GTMvg5_VLhS_feF6b6OGZ4iV3etEbjE',
    appId: '1:862942068538:web:771e3ede0c4c38a8931a03',
    messagingSenderId: '862942068538',
    projectId: 'coffee-log-b5909',
    authDomain: 'coffee-log-b5909.firebaseapp.com',
    storageBucket: 'coffee-log-b5909.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyADj6hAtY4QgWnge14KI-o1jw5ws-PYccU',
    appId: '1:862942068538:android:86be320d102703c5931a03',
    messagingSenderId: '862942068538',
    projectId: 'coffee-log-b5909',
    storageBucket: 'coffee-log-b5909.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDjw_mOk7Hs5UrPnZ_mrLPbNUW1I0PMW3U',
    appId: '1:862942068538:ios:a0f8dae5dacca0c7931a03',
    messagingSenderId: '862942068538',
    projectId: 'coffee-log-b5909',
    storageBucket: 'coffee-log-b5909.appspot.com',
    iosClientId: '862942068538-upe91r7e6h57lmgub8k0o3l0dg31rb2c.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeLog',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDjw_mOk7Hs5UrPnZ_mrLPbNUW1I0PMW3U',
    appId: '1:862942068538:ios:fcb34ac2d90b968f931a03',
    messagingSenderId: '862942068538',
    projectId: 'coffee-log-b5909',
    storageBucket: 'coffee-log-b5909.appspot.com',
    iosClientId: '862942068538-22rlkjt370q2cp4h40at2b15vropm3bu.apps.googleusercontent.com',
    iosBundleId: 'com.example.coffeeLog.RunnerTests',
  );
}
